server:
  port: 8081
#数据源
spring:
  application:
    name: e-admin-consumer
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encding: UTF-8
#指向注册中心
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
    instance:
      prefer-ip-address: true
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

e-admin-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule