server:
      port: 8082
spring:
  application:
    name: dm-user-provider
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/

dm-user-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
